name: Build and Deploy
on: # ç›‘å¬ master åˆ†æ”¯ä¸Šçš„ push äº‹ä»¶
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # æ„å»ºç¯å¢ƒä½¿ç”¨ ubuntu
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1  # ä½¿ç”¨åˆ«äººå†™å¥½çš„ actions
        with:
          persist-credentials: false

      - name: Install and Build ğŸ”§ # ä¸‹è½½ä¾èµ– æ‰“åŒ…é¡¹ç›®
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€ # å°†æ‰“åŒ…å†…å®¹å‘å¸ƒåˆ° github page
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:  # è‡ªå®šä¹‰ç¯å¢ƒå˜é‡
          ACCESS_TOKEN: ${{ secrets.VUE_ADMIN_TEMPLATE }}
          BRANCH: master
          FOLDER: dist
          REPOSITORY_NAME: woai3c/woai3c.github.io # è¿™æ˜¯æˆ‘çš„ github page åœ°å€
          TARGET_FOLDER: github-actions-demo